### ISSUE TITLE
Add-on not marked as compatible with Android.

### ISSUE THREAD

**Issue by PhantomGamers** [hyperstown/twitter-pwa-fix#1]
I'm not sure if this is intentional, since the Readme says it's coming soon, but the repo itself has a link to an add-on that doesn't appear on the store in the Firefox Android browser.

I would love this add-on, as the white notification bar is quite jarring.

**Comment by hyperstown** [comment]
Thanks for the report. I submitted a new version to Firefox. ~~It should be out in >24h.~~

~~If you don't want to wait you can force desktop mode on add-on page and you should be able to install it right now.~~

It's already out.
