### ISSUE TITLE
Nav bar color unchanged

### ISSUE THREAD

**Issue by PhantomGamers** [hyperstown/twitter-pwa-fix#2]
Thanks for fixing the previous issue of the add-on not being available in the store. This definitely improves the experience of using the PWA.

However, while the notification bar is darkened now, the navigation bar still appears white. Is this fixable?

![Screenshot_20240409_173857_Firefox.jpg](https://github.com/hyperstown/twitter-pwa-fix/assets/844685/9d5df00c-fe51-4a3f-9adb-788e1cfe6a4f)

**Comment by hyperstown** [comment]
It looks like there's an issue with Firefox 124. I couldn't reproduce this issue but then I noticed I'm running version 123. Once updated I got exactly the same issue. It also happens on all PWAs. It seems that version 125+ also solves this issue. Both Firefox Beta and Firefox Nightly work just fine.
For now I'll leave this issue open. Once Mozilla fixes this issue I'll close it.

**Comment by PhantomGamers** [comment]
The update is out on stable now, so this is fixed! :)
